{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.7.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"# Content available in page https://analyticsindiamag.com/a-guide-to-inferencing-with-bayesian-network-in-python/\n# PACKAGE INSTALLATION AND LOADING\n!pip install pgmpy","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","trusted":true},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"# from pgmpy.model2s import BayesianNetwork\nfrom pgmpy.inference import VariableElimination\nfrom pgmpy.models import BayesianNetwork\nfrom pgmpy.factors.discrete import TabularCPD\nimport networkx as nx\n# import pylab as plt\nimport matplotlib.pyplot as plt","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2022-09-14T12:40:05.212898Z","iopub.execute_input":"2022-09-14T12:40:05.213347Z","iopub.status.idle":"2022-09-14T12:42:35.176321Z","shell.execute_reply.started":"2022-09-14T12:40:05.2133Z","shell.execute_reply":"2022-09-14T12:42:35.174367Z"},"trusted":true},"execution_count":2,"outputs":[{"name":"stdout","text":"\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f692bee9510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f692beb2f90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f692beb2710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f692beb2850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f692beb2d50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[31mERROR: Could not find a version that satisfies the requirement pgmpy (from versions: none)\u001b[0m\u001b[31m\n\u001b[0m\u001b[31mERROR: No matching distribution found for pgmpy\u001b[0m\u001b[31m\n\u001b[0m\u001b[33mWARNING: There was an error checking the latest version of pip.\u001b[0m\u001b[33m\n\u001b[0m","output_type":"stream"},{"traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)","\u001b[0;32m/tmp/ipykernel_18/2056277890.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mget_ipython\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msystem\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'pip install pgmpy'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;31m# from pgmpy.model2s import BayesianNetwork\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mpgmpy\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minference\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mVariableElimination\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      6\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mpgmpy\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodels\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mBayesianNetwork\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mpgmpy\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfactors\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdiscrete\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mTabularCPD\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'pgmpy'"],"ename":"ModuleNotFoundError","evalue":"No module named 'pgmpy'","output_type":"error"}]},{"cell_type":"code","source":"","metadata":{},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"# Defining Bayesian Structure\n# arcs from the cause to the effect\nmodel = BayesianNetwork([('hasKnowledgment', 'correctAnswer_Q01')])","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2022-09-14T12:37:03.016636Z","iopub.execute_input":"2022-09-14T12:37:03.017799Z"},"trusted":true},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"# Defining the CPDs:\n# PRIORS\ncpd_hasKnowledgment = TabularCPD(variable='hasKnowledgment',\n                                 variable_card=2, values=[[.5], [.5]], state_names={\"hasKnowledgment\": [\"YES\", \"NO\"]})  # 0- yes, 1-no\nprint(cpd_hasKnowledgment)","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2022-09-14T12:37:03.016636Z","iopub.execute_input":"2022-09-14T12:37:03.017799Z"},"trusted":true},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"# LIKELIHOODS: mede o poder de causa e efeito entre as v√°riaveis\ncpd_correctAnswer_Q01 = TabularCPD(variable='correctAnswer_Q01',\n                                   variable_card=2, values=[[.9, .25],  # 0- yes, 1-no\n                                                            [.1, .75]],\n                                   evidence=['hasKnowledgment'], evidence_card=[2],\n                                   state_names={\"hasKnowledgment\": [\"YES\", \"NO\"],\n                                                \"correctAnswer_Q01\": [\"YES\", \"NO\"]})\nprint(cpd_correctAnswer_Q01)","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2022-09-14T12:37:03.016636Z","iopub.execute_input":"2022-09-14T12:37:03.017799Z"},"trusted":true},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"# Associating the CPDs with the network structure.\nmodel.add_cpds(cpd_hasKnowledgment, cpd_correctAnswer_Q01)\nmodel.check_model()","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2022-09-14T12:37:03.016636Z","iopub.execute_input":"2022-09-14T12:37:03.017799Z"},"trusted":true},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"# PLOT THE MODEL\nnx.draw(model, with_labels=True)\nplt.show()\n# plt.savefig('BBN_model.png')\n# plt.close()","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2022-09-14T12:37:03.016636Z","iopub.execute_input":"2022-09-14T12:37:03.017799Z"},"trusted":true},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"# BBN (for qualitative analysis)\n# COMPUTING THE POSTERIOR/MARGINAL DISTRIBUTIONS\n\ninfer = VariableElimination(model)\nposterior_p = infer.query(['hasKnowledgment'], evidence={\n                          'correctAnswer_Q01': 'YES'})\nprint(posterior_p)","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2022-09-14T12:37:03.016636Z","iopub.execute_input":"2022-09-14T12:37:03.017799Z"},"trusted":true},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"# INVOLVING A SECOND QUESTION, MORE DIFFICULT TO ANSWER...\nmodel2 = BayesianNetwork([('hasKnowledgment', 'correctAnswer_Q01'),\n                          ('hasKnowledgment', 'correctAnswer_Q02')])  # arcs from the cause to the effect\n# Defining the CPDs:\n# PRIORS\ncpd_hasKnowledgment = TabularCPD(variable='hasKnowledgment',\n                                 variable_card=2, values=[[.5], [.5]], state_names={\"hasKnowledgment\": [\"YES\", \"NO\"]})  # 0- yes, 1-no\nprint(cpd_hasKnowledgment)\n# LIKELIHOODS\ncpd_correctAnswer_Q01 = TabularCPD(variable='correctAnswer_Q01',\n                                   variable_card=2, values=[[.9, .25],  # 0- yes, 1-no\n                                                            [.1, .75]],\n                                   evidence=['hasKnowledgment'], evidence_card=[2],\n                                   state_names={\"hasKnowledgment\": [\"YES\", \"NO\"],\n                                                \"correctAnswer_Q01\": [\"YES\", \"NO\"]})\nprint(cpd_correctAnswer_Q01)\ncpd_correctAnswer_Q02 = TabularCPD(variable='correctAnswer_Q02',\n                                   variable_card=2, values=[[.9, .25],  # 0- yes, 1-no\n                                                            [.1, .75]],\n                                   evidence=['hasKnowledgment'], evidence_card=[2],\n                                   state_names={\"hasKnowledgment\": [\"YES\", \"NO\"],\n                                                \"correctAnswer_Q02\": [\"YES\", \"NO\"]})\nprint(cpd_correctAnswer_Q02)\n# Associating the CPDs with the network structure.\nmodel2.add_cpds(cpd_hasKnowledgment, cpd_correctAnswer_Q01,\n                cpd_correctAnswer_Q02)\nmodel2.check_model()\n# BBN (for qualitative analysis)\n# COMPUTING THE POSTERIOR/MARGINAL DISTRIBUTIONS\n# from pgmpy.inference import VariableElimination\n\ninfer = VariableElimination(model2)\nposterior_p2 = infer.query(['hasKnowledgment'], evidence={\n                           'correctAnswer_Q01': 'YES', 'correctAnswer_Q02': 'YES'})\nprint(posterior_p2)","metadata":{"_uuid":"8f2839f25d086af736a60e9eeb907d3b93b6e0e5","_cell_guid":"b1076dfc-b9ad-4769-8c92-a6c4dae69d19","execution":{"iopub.status.busy":"2022-09-14T12:37:03.016636Z","iopub.execute_input":"2022-09-14T12:37:03.017799Z"},"trusted":true},"execution_count":null,"outputs":[{"name":"stdout","text":"\u001b[33mWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb7062af50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb7060bcd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb7060b390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb7060b410>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[33mWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7fcb705f61d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pgmpy/\u001b[0m\u001b[33m\n\u001b[0m\u001b[31mERROR: Could not find a version that satisfies the requirement pgmpy (from versions: none)\u001b[0m\u001b[31m\n\u001b[0m\u001b[31mERROR: No matching distribution found for pgmpy\u001b[0m\u001b[31m\n\u001b[0m","output_type":"stream"}]}]}